#!/usr/bin/env bash
service_name="$(basename -- $PWD)"
docker exec -it $service_name php artisan "$@"
echo '++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++'
echo "Artisan command finished on $service_name"
echo '++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++'
