#!/usr/bin/env bash
service_name="$(basename -- $PWD)"
docker exec -it $service_name composer "$@"
echo '++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++'
echo "Composer command finished on $service_name"
echo '++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++'
