#!/usr/bin/env bash

docker-compose stop
echo '++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++'
docker ps -a --format "table {{.Names}}\t{{.Ports}}\t{{.Image}}\t{{.ID}}\t{{.Status}}"
echo '++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++'
